### ISSUE TITLE
There is QtWebKit 5.212.0 Alpha 3

### ISSUE THREAD

**Issue by carlosgonz0** [llelectronics/lls-qtwebkit#2]
https://github.com/qtwebkit/qtwebkit

**Comment by llelectronics** [comment]
Wich is old

**Comment by carlosgonz0** [comment]
well, it was released 5 month ago, @llelectronics could we get benefits on that version?

**Comment by llelectronics** [comment]
Qtwebkit here is based already on it

**Comment by carlosgonz0** [comment]
> Qtwebkit here is based already on it

Yes I already know that your qtwebkit is based on it. But your qtwebkit is alpha2 and this is a newer version alpha3, If qtwebkit5212alpha3 come with many fixes will make sense update it to alpha3?

**Comment by llelectronics** [comment]
This is not alpha2. It is started with alpha2 but was gradually updated to alpha3

**Comment by carlosgonz0** [comment]
aahhh ok. thank you for update it to alpha3.
@llelectronics do you know if this qtwebkit is supporting egl or something like that for a smoothing scroll?

**Comment by carlosgonz0** [comment]
Actually in webcat the  webpage is stutering. What is the solution for it?

**Comment by llelectronics** [comment]
There is no real solution for it I fear. I updated it to be as smooth as possible by tweaking the caching and tile caching algorithms. But there are some limits. 
First of all it uses a bit more CPU than you usually use on a mobile phone. The other issue is a general bug in the scrolling algorithm which updates the page not constantly while scrolling (this is why some top or bottom bars fixed on the website jump up and down a few times)
As for why it is not using the GPU only it has something to do with the BGRA implementation in the Sony Xperia devices. They seem to have no or buggy support for this. 
So the CPU needs to calculate and translate BGRA to RGBA which leads to higher CPU usage on those devices. 

This is why Jolla1 and Jolla C usually have a perceived smoother scrolling with Webcat.

**Comment by carlosgonz0** [comment]
Thank you.
Stay Sailfish.

**Comment by carlosgonz0** [comment]
https://git.sailfishos.org/mer-core/qtbase/merge_requests/54

newer release QtWebKit 5.212.0 Alpha 4  https://github.com/qtwebkit/qtwebkit
